export function guessNationality(
  country: string | null | undefined,
): string | null {
  if (!country) return null;
  for (const c of country.split(",")) {
    const normalized = c.trim().toLowerCase();
    if (normalized in demonyms) {
      return demonyms[normalized];
    }
  }
  return country;
}

const demonyms: Record<string, string> = {
  // https://en.wikipedia.org/wiki/List_of_adjectival_and_demonymic_forms_for_countries_and_nations
  abkhaz: "Abkhazia",
  abkhazian: "Abkhazia",
  afghan: "Afghanistan",
  "african american": "United States",
  albanian: "Albania",
  algerian: "Algeria",
  "american samoan": "American Samoa",
  american: "United States",
  andorran: "Andorra",
  angolan: "Angola",
  anguillan: "Anguilla",
  antarctic: "Antarctica",
  antiguan: "Antigua and Barbuda",
  argentine: "Argentina",
  argentinian: "Argentina",
  armenian: "Armenia",
  aruban: "Aruba",
  australian: "Australia",
  austrian: "Austria",
  azerbaijani: "Azerbaijan",
  azeri: "Azerbaijan",
  bahamian: "Bahamas",
  bahraini: "Bahrain",
  bangladeshi: "Bangladesh",
  barbadian: "Barbados",
  barbudan: "Antigua and Barbuda",
  basotho: "Lesotho",
  belarusian: "Belarus",
  belgian: "Belgium",
  belizean: "Belize",
  beninese: "Benin",
  beninois: "Benin",
  bermudan: "Bermuda",
  bermudian: "Bermuda",
  bhutanese: "Bhutan",
  biot: "British Indian Ocean Territory",
  "bissau-guinean": "Guinea-Bissau",
  bolivian: "Bolivia",
  bonaire: "Bonaire",
  bonairean: "Bonaire",
  bosnian: "Bosnia and Herzegovina",
  botswanan: "Botswana",
  "bouvet island": "Bouvet Island",
  brazilian: "Brazil",
  "british virgin island": "Virgin Islands, British",
  british: "United Kingdom",
  bruneian: "Brunei",
  bulgarian: "Bulgaria",
  burkinabé: "Burkina Faso",
  burmese: "Burma",
  burundian: "Burundi",
  "cabo verdean": "Cabo Verde",
  cambodian: "Cambodia",
  cameroonian: "Cameroon",
  canadian: "Canada",
  cantonese: "Hong Kong",
  caymanian: "Cayman Islands",
  "central african": "Central African Republic",
  chadian: "Chad",
  "channel island": "Guernsey",
  chilean: "Chile",
  chinese: "China",
  "christmas island": "Christmas Island",
  "cocos island": "Cocos (Keeling) Islands",
  colombian: "Colombia",
  comoran: "Comoros",
  comorian: "Comoros",
  congolese: "Congo",
  "cook island": "Cook Islands",
  "costa rican": "Costa Rica",
  croatian: "Croatia",
  cuban: "Cuba",
  curaçaoan: "Curaçao",
  cypriot: "Cyprus",
  czech: "Czech Republic",
  danish: "Denmark",
  djiboutian: "Djibouti",
  dominican: "Dominica",
  dutch: "Netherlands",
  ecuadorian: "Ecuador",
  egyptian: "Egypt",
  emirati: "United Arab Emirates",
  emiri: "United Arab Emirates",
  emirian: "United Arab Emirates",
  "english people": "England",
  english: "England",
  equatoguinean: "Equatorial Guinea",
  "equatorial guinean": "Equatorial Guinea",
  eritrean: "Eritrea",
  estonian: "Estonia",
  ethiopian: "Ethiopia",
  european: "European Union",
  "falkland island": "Falkland Islands",
  faroese: "Faroe Islands",
  fijian: "Fiji",
  filipino: "Philippines",
  finnish: "Finland",
  formosan: "Taiwan",
  "french guianese": "French Guiana",
  "french polynesian": "French Polynesia",
  "french southern territories": "French Southern Territories",
  french: "France",
  futunan: "Wallis and Futuna",
  gabonese: "Gabon",
  gambian: "Gambia",
  georgian: "Georgia",
  german: "Germany",
  ghanaian: "Ghana",
  gibraltar: "Gibraltar",
  greek: "Greece",
  greenlandic: "Greenland",
  grenadian: "Grenada",
  guadeloupe: "Guadeloupe",
  guamanian: "Guam",
  guatemalan: "Guatemala",
  guinean: "Guinea",
  guyanese: "Guyana",
  haitian: "Haiti",
  "heard island": "Heard Island and McDonald Islands",
  hellenic: "Greece",
  herzegovinian: "Bosnia and Herzegovina",
  honduran: "Honduras",
  "hong kong": "Hong Kong",
  "hong konger": "Hong Kong",
  hungarian: "Hungary",
  icelandic: "Iceland",
  indian: "India",
  indonesian: "Indonesia",
  iranian: "Iran",
  iraqi: "Iraq",
  irish: "Ireland",
  israeli: "Israel",
  israelite: "Israel",
  italian: "Italy",
  ivorian: "Ivory Coast",
  jamaican: "Jamaica",
  "jan mayen": "Jan Mayen",
  japanese: "Japan",
  jordanian: "Jordan",
  kazakh: "Kazakhstan",
  kazakhstani: "Kazakhstan",
  kenyan: "Kenya",
  kirghiz: "Kyrgyzstan",
  kirgiz: "Kyrgyzstan",
  kiribati: "Kiribati",
  korean: "South Korea",
  kosovan: "Kosovo",
  kosovar: "Kosovo",
  kuwaiti: "Kuwait",
  kyrgyz: "Kyrgyzstan",
  kyrgyzstani: "Kyrgyzstan",
  lao: "Lao People's Democratic Republic",
  laotian: "Lao People's Democratic Republic",
  latvian: "Latvia",
  lebanese: "Lebanon",
  lettish: "Latvia",
  liberian: "Liberia",
  libyan: "Libya",
  liechtensteiner: "Liechtenstein",
  lithuanian: "Lithuania",
  luxembourg: "Luxembourg",
  luxembourgish: "Luxembourg",
  macanese: "Macau",
  macedonian: "North Macedonia",
  magyar: "Hungary",
  mahoran: "Mayotte",
  malagasy: "Madagascar",
  malawian: "Malawi",
  malaysian: "Malaysia",
  maldivian: "Maldives",
  malian: "Mali",
  malinese: "Mali",
  maltese: "Malta",
  manx: "Isle of Man",
  marshallese: "Marshall Islands",
  martinican: "Martinique",
  martiniquais: "Martinique",
  mauritanian: "Mauritania",
  mauritian: "Mauritius",
  "mcdonald islands": "Heard Island and McDonald Islands",
  mexican: "Mexico",
  moldovan: "Moldova",
  monacan: "Monaco",
  mongolian: "Mongolia",
  montenegrin: "Montenegro",
  montserratian: "Montserrat",
  monégasque: "Monaco",
  moroccan: "Morocco",
  motswana: "Botswana",
  mozambican: "Mozambique",
  myanma: "Myanmar",
  namibian: "Namibia",
  nauruan: "Nauru",
  nepalese: "Nepal",
  nepali: "Nepal",
  netherlandic: "Netherlands",
  "new caledonian": "New Caledonia",
  "new zealand": "New Zealand",
  "ni-vanuatu": "Vanuatu",
  nicaraguan: "Nicaragua",
  nigerian: "Nigeria",
  nigerien: "Niger",
  niuean: "Niue",
  "norfolk island": "Norfolk Island",
  "northern irish": "Northern Ireland",
  "northern marianan": "Northern Mariana Islands",
  norwegian: "Norway",
  omani: "Oman",
  pakistani: "Pakistan",
  palauan: "Palau",
  palestinian: "Palestine",
  panamanian: "Panama",
  "papua new guinean": "Papua New Guinea",
  papuan: "Papua New Guinea",
  paraguayan: "Paraguay",
  persian: "Iran",
  peruvian: "Peru",
  philippine: "Philippines",
  "pitcairn island": "Pitcairn Islands",
  polish: "Poland",
  portuguese: "Portugal",
  "puerto rican": "Puerto Rico",
  qatari: "Qatar",
  romanian: "Romania",
  russian: "Russia",
  rwandan: "Rwanda",
  saba: "Saba",
  saban: "Saba",
  sahraouian: "Western Sahara",
  sahrawi: "Western Sahara",
  sahrawian: "Western Sahara",
  salvadoran: "El Salvador",
  sammarinese: "San Marino",
  samoan: "Samoa",
  "saudi arabian": "Saudi Arabia",
  saudi: "Saudi Arabia",
  scottish: "Scotland",
  senegalese: "Senegal",
  serbian: "Serbia",
  seychellois: "Seychelles",
  "sierra leonean": "Sierra Leone",
  singapore: "Singapore",
  singaporean: "Singapore",
  slovak: "Slovakia",
  slovene: "Slovenia",
  slovenian: "Slovenia",
  "solomon island": "Solomon Islands",
  somali: "Somalia",
  somalilander: "Somaliland",
  "south african": "South Africa",
  "south georgia island": "South Georgia and the South Sandwich Islands",
  "south ossetian": "South Ossetia",
  "south sandwich island": "South Georgia and the South Sandwich Islands",
  "south sudanese": "South Sudan",
  spanish: "Spain",
  "sri lankan": "Sri Lanka",
  sudanese: "Sudan",
  surinamese: "Suriname",
  "svalbard resident": "Svalbard",
  swati: "Eswatini",
  swazi: "Eswatini",
  swedish: "Sweden",
  swiss: "Switzerland",
  syrian: "Syrian Arab Republic",
  taiwanese: "Taiwan",
  tajikistani: "Tajikistan",
  tanzanian: "Tanzania",
  thai: "Thailand",
  timorese: "Timor-Leste",
  tobagonian: "Trinidad and Tobago",
  togolese: "Togo",
  tokelauan: "Tokelau",
  tongan: "Tonga",
  trinidadian: "Trinidad and Tobago",
  tunisian: "Tunisia",
  turkish: "Turkey",
  turkmen: "Turkmenistan",
  "turks and caicos island": "Turks and Caicos Islands",
  tuvaluan: "Tuvalu",
  ugandan: "Uganda",
  ukrainian: "Ukraine",
  uruguayan: "Uruguay",
  uzbek: "Uzbekistan",
  uzbekistani: "Uzbekistan",
  vanuatuan: "Vanuatu",
  vatican: "Vatican City State",
  venezuelan: "Venezuela",
  vietnamese: "Vietnam",
  "wallis and futuna": "Wallis and Futuna",
  wallisian: "Wallis and Futuna",
  welsh: "Wales",
  yemeni: "Yemen",
  zambian: "Zambia",
  zimbabwean: "Zimbabwe",
  "åland island": "Åland Islands",
  "united states": "United States",
  usa: "United States",
  af: "Afghanistan",
  ax: "Åland Islands",
  al: "Albania",
  dz: "Algeria",
  as: "American Samoa",
  ad: "Andorra",
  ao: "Angola",
  ai: "Anguilla",
  aq: "Antarctica",
  ag: "Antigua and Barbuda",
  ar: "Argentina",
  am: "Armenia",
  aw: "Aruba",
  au: "Australia",
  at: "Austria",
  az: "Azerbaijan",
  bs: "Bahamas",
  bh: "Bahrain",
  bd: "Bangladesh",
  bb: "Barbados",
  by: "Belarus",
  be: "Belgium",
  bz: "Belize",
  bj: "Benin",
  bm: "Bermuda",
  bt: "Bhutan",
  bo: "Bolivia",
  bq: "Bonaire, Sint Eustatius and Saba",
  ba: "Bosnia and Herzegovina",
  bw: "Botswana",
  bv: "Bouvet Island",
  br: "Brazil",
  io: "British Indian Ocean Territory",
  bn: "Brunei Darussalam",
  bg: "Bulgaria",
  bf: "Burkina Faso",
  bi: "Burundi",
  cv: "Cabo Verde",
  kh: "Cambodia",
  cm: "Cameroon",
  ca: "Canada",
  ky: "Cayman Islands",
  cf: "Central African Republic",
  td: "Chad",
  cl: "Chile",
  cn: "China",
  cx: "Christmas Island",
  cc: "Cocos (Keeling) Islands",
  co: "Colombia",
  km: "Comoros",
  cd: "Congo (the Democratic Republic of the)",
  cg: "Congo",
  ck: "Cook Islands",
  cr: "Costa Rica",
  ci: "Côte d'Ivoire",
  hr: "Croatia",
  cu: "Cuba",
  cw: "Curaçao",
  cy: "Cyprus",
  cz: "Czechia",
  dk: "Denmark",
  dj: "Djibouti",
  dm: "Dominica",
  do: "Dominican Republic",
  ec: "Ecuador",
  eg: "Egypt",
  sv: "El Salvador",
  gq: "Equatorial Guinea",
  er: "Eritrea",
  ee: "Estonia",
  sz: "Eswatini",
  et: "Ethiopia",
  fk: "Falkland Islands",
  fo: "Faroe Islands",
  fj: "Fiji",
  fi: "Finland",
  fr: "France",
  gf: "French Guiana",
  pf: "French Polynesia",
  tf: "French Southern Territories",
  ga: "Gabon",
  gm: "Gambia",
  ge: "Georgia",
  de: "Germany",
  gh: "Ghana",
  gi: "Gibraltar",
  gr: "Greece",
  gl: "Greenland",
  gd: "Grenada",
  gp: "Guadeloupe",
  gu: "Guam",
  gt: "Guatemala",
  gg: "Guernsey",
  gn: "Guinea",
  gw: "Guinea-Bissau",
  gy: "Guyana",
  ht: "Haiti",
  hm: "Heard Island and McDonald Islands",
  va: "Holy See",
  hn: "Honduras",
  hk: "Hong Kong",
  hu: "Hungary",
  is: "Iceland",
  in: "India",
  id: "Indonesia",
  ir: "Iran",
  iq: "Iraq",
  ie: "Ireland",
  im: "Isle of Man",
  il: "Israel",
  it: "Italy",
  jm: "Jamaica",
  jp: "Japan",
  je: "Jersey",
  jo: "Jordan",
  kz: "Kazakhstan",
  ke: "Kenya",
  ki: "Kiribati",
  kp: "Korea (the Democratic People's Republic of)",
  kr: "Korea (the Republic of)",
  kw: "Kuwait",
  kg: "Kyrgyzstan",
  la: "Lao People's Democratic Republic",
  lv: "Latvia",
  lb: "Lebanon",
  ls: "Lesotho",
  lr: "Liberia",
  ly: "Libya",
  li: "Liechtenstein",
  lt: "Lithuania",
  lu: "Luxembourg",
  mo: "Macao",
  mk: "Republic of North Macedonia",
  mg: "Madagascar",
  mw: "Malawi",
  my: "Malaysia",
  mv: "Maldives",
  ml: "Mali",
  mt: "Malta",
  mh: "Marshall Islands",
  mq: "Martinique",
  mr: "Mauritania",
  mu: "Mauritius",
  yt: "Mayotte",
  mx: "Mexico",
  fm: "Micronesia (Federated States of)",
  md: "Moldova (the Republic of)",
  mc: "Monaco",
  mn: "Mongolia",
  me: "Montenegro",
  ms: "Montserrat",
  ma: "Morocco",
  mz: "Mozambique",
  mm: "Myanmar",
  na: "Namibia",
  nr: "Nauru",
  np: "Nepal",
  nl: "Netherlands",
  nc: "New Caledonia",
  nz: "New Zealand",
  ni: "Nicaragua",
  ne: "Niger",
  ng: "Nigeria",
  nu: "Niue",
  nf: "Norfolk Island",
  mp: "Northern Mariana Islands",
  no: "Norway",
  om: "Oman",
  pk: "Pakistan",
  pw: "Palau",
  ps: "Palestine, State of",
  pa: "Panama",
  pg: "Papua New Guinea",
  py: "Paraguay",
  pe: "Peru",
  ph: "Philippines",
  pn: "Pitcairn",
  pl: "Poland",
  pt: "Portugal",
  pr: "Puerto Rico",
  qa: "Qatar",
  re: "Réunion",
  ro: "Romania",
  ru: "Russian Federation",
  rw: "Rwanda",
  bl: "Saint Barthélemy",
  sh: "Saint Helena, Ascension and Tristan da Cunha",
  kn: "Saint Kitts and Nevis",
  lc: "Saint Lucia",
  mf: "Saint Martin (French part)",
  pm: "Saint Pierre and Miquelon",
  vc: "Saint Vincent and the Grenadines",
  ws: "Samoa",
  sm: "San Marino",
  st: "Sao Tome and Principe",
  sa: "Saudi Arabia",
  sn: "Senegal",
  rs: "Serbia",
  sc: "Seychelles",
  sl: "Sierra Leone",
  sg: "Singapore",
  sx: "Sint Maarten (Dutch part)",
  sk: "Slovakia",
  si: "Slovenia",
  sb: "Solomon Islands",
  so: "Somalia",
  za: "South Africa",
  gs: "South Georgia and the South Sandwich Islands",
  ss: "South Sudan",
  es: "Spain",
  lk: "Sri Lanka",
  sd: "Sudan",
  sr: "Suriname",
  sj: "Svalbard and Jan Mayen",
  se: "Sweden",
  ch: "Switzerland",
  sy: "Syrian Arab Republic",
  tw: "Taiwan",
  tj: "Tajikistan",
  tz: "Tanzania, United Republic of",
  th: "Thailand",
  tl: "Timor-Leste",
  tg: "Togo",
  tk: "Tokelau",
  to: "Tonga",
  tt: "Trinidad and Tobago",
  tn: "Tunisia",
  tr: "Turkey",
  tm: "Turkmenistan",
  tc: "Turks and Caicos Islands",
  tv: "Tuvalu",
  ug: "Uganda",
  ua: "Ukraine",
  ae: "United Arab Emirates",
  gb: "United Kingdom of Great Britain and Northern Ireland",
  um: "United States Minor Outlying Islands",
  us: "United States",
  uy: "Uruguay",
  uz: "Uzbekistan",
  vu: "Vanuatu",
  ve: "Venezuela (Bolivarian Republic of)",
  vn: "Viet Nam",
  vg: "Virgin Islands (British)",
  vi: "Virgin Islands (U.S.)",
  wf: "Wallis and Futuna",
  eh: "Western Sahara",
  ye: "Yemen",
  zm: "Zambia",
  zw: "Zimbabwe",
};
